### ISSUE TITLE
Citizens and leaders bugs

### ISSUE THREAD

**Issue by jessepincay** [hpfxd/PandaSpigot#138]
citizens npc's disappear randomly for a few seconds or minutes, it is unpredictable.
tops with leaderheads armor supports become normal supports or disappear.
and sometimes holograms show an armor support for a fraction of a second.

plugin leaderheads: https://www.spigotmc.org/resources/leaderheads.2079/
citizens: https://www.spigotmc.org/resources/citizens.13811/

**Comment by mechoriet** [comment]
#141 should fix the first part of your issue

the second part can't test since Its a paid plugin and I don't have it

**Comment by jessepincay** [comment]
You can use the dev versions.
These are the ones I currently use.

**Comment by uRyanxD** [comment]
@jessepincay Does the problem with LeaderHeads still occur even after commit 8b97cd9?

**Comment by AIGLE25** [comment]
> #141 should fix the first part of your issue
> 
> the second part can't test since Its a paid plugin and I don't have it

not a paid plugin

**Comment by F3F5** [comment]
> @jessepincay Does the problem with LeaderHeads still occur even after commit [8b97cd9](https://github.com/hpfxd/PandaSpigot/commit/8b97cd996364b9bc4ba31272388595a86d253c1b)?

https://ci.citizensnpcs.co/job/Citizens2/

**Comment by uRyanxD** [comment]
> > @jessepincay Does the problem with LeaderHeads still occur even after commit [8b97cd9](https://github.com/hpfxd/PandaSpigot/commit/8b97cd996364b9bc4ba31272388595a86d253c1b)?
> 
> https://ci.citizensnpcs.co/job/Citizens2/

I need LeaderHeads, not Citizens

**Comment by Obydux** [comment]
LeaderHeads isn't open source and can't be purchased or downloaded anymore
